### ISSUE TITLE
Level 2 header gets on the same line as level 1

### ISSUE THREAD

**Issue by cbertelli** [joedf/strapdown-topbar#7]
If I don't use strapdown-topbar it does not happen, but adding it has this strange effect.

without topbar
![Imgur](http://i.imgur.com/5Iarcql.png)

with top bar
![Imgur](http://i.imgur.com/YxMmfpN.png)

**Comment by joedf** [comment]
Could you send me a zip of the generated html (browser: Save as...).
Sorry for the late reply, been rather busy

**Comment by cbertelli** [comment]
I uploaded the original source and the generated one. Thanks for replying anyway.
[workinprogresswhatisthis.zip](https://github.com/joedf/strapdown-topbar/files/1220335/workinprogresswhatisthis.zip)

**Comment by joedf** [comment]
Thanks!
Yes, I see the problem is the headers (h1,h2,h3,...) are set with `display: inline-block;`. A quick fix without breaking the styles too much is adding a `<br/>` tag in front of all anchored/linked headers.
Try it with this test version?
[strapdown-topbar.custom001.js.zip](https://github.com/joedf/strapdown-topbar/files/1220981/strapdown-topbar.custom001.js.zip)

**Comment by cbertelli** [comment]
Hello,
yes, it works. It was the same solution I choose, adding a <br /> tag after
the first header which is usually followed by a lower lever header.
c
